"""LiveKit Agents entrypoint (architecture §1, §2): WebRTC transport, VAD,
Deepgram STT, turn handling, barge-in -> orchestrator.py -> Rime TTS
(LiveKit's official Rime plugin) -> playback -> telemetry.

VERIFY BEFORE THE RECORDED DEMO (architecture §3 already requires a live
end-to-end pass, so treat this as part of that): the exact turn-handling
event names/signatures below (`on_user_turn_completed`, `StopResponse`,
`user_interruption_detected`) were confirmed against docs.livekit.io at
build time for livekit-agents ~1.5, but this framework's turn API has moved
fast across versions -- pin the version in requirements.txt and re-check
against the SDK actually installed.

Run: python livekit_agent.py dev   (or `start` for production)
"""

import asyncio
import logging

from livekit import agents
from livekit.agents import Agent, AgentServer, AgentSession
from livekit.plugins import deepgram, rime, silero

try:
    from livekit.agents import StopResponse
except ImportError:  # pragma: no cover - fallback if the symbol moves
    class StopResponse(Exception):
        """Raised from on_user_turn_completed to skip the framework's own
        LLM continuation, since we generate every answer ourselves via
        orchestrator.py + sql_rag_chain.py."""

import config
import fallback_tts
import orchestrator as orchestrator_module
import sql_rag_chain
import telemetry

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("livekit_agent")

FAILURE_SPEECH = (
    "Sorry, I couldn't safely answer that from the hardware database. "
    "Could you rephrase the question?"
)

server = AgentServer()


class LabAssistant(Agent):
    """Owns no LLM of its own -- every spoken answer is generated by
    orchestrator.py + sql_rag_chain.py so generation-ID fencing stays in one
    place (architecture §2.1)."""

    def __init__(self, orch: orchestrator_module.Orchestrator, room) -> None:
        super().__init__(
            instructions=(
                "You are a voice assistant for a mechatronics lab. You only "
                "answer hardware spec questions using the SQL-RAG tool; you "
                "never guess at a spec."
            )
        )
        self.orch = orch
        self.room = room

    async def on_user_turn_completed(self, turn_ctx, new_message) -> None:
        text = (getattr(new_message, "text_content", None) or "").strip()
        if not text:
            raise StopResponse()

        gen = self.orch.start_new_turn(text)

        try:
            result = await self.orch.run_sql_rag(text, gen)
        except sql_rag_chain.UnsafeSQLError:
            logger.warning("UnsafeSQLError for %r", text)
            await self._speak_if_current(gen, FAILURE_SPEECH)
            raise StopResponse()
        except Exception:
            logger.exception("SQL-RAG/DB failure for %r", text)
            await self._speak_if_current(gen, FAILURE_SPEECH)
            raise StopResponse()

        if result is None:
            # Fenced: a newer turn already started while this one was
            # in flight. Per architecture §2.1, never speak a stale result.
            self.orch.finish_turn_without_speech(gen)
            raise StopResponse()

        await self._speak_if_current(gen, result.answer)
        raise StopResponse()

    async def _speak_if_current(self, generation_id: int, text: str) -> None:
        if not self.orch.begin_playback(generation_id, text):
            return  # fenced -- must not speak

        try:
            handle = self.session.say(text, allow_interruptions=True)
        except Exception:
            logger.exception("Rime TTS failed, falling back")
            telemetry.log_speech_provider("fallback")
            self.orch.finish_playback(generation_id)
            await fallback_tts.speak_fallback(self.room, config.FALLBACK_APOLOGY_TEXT)
            return

        telemetry.log_speech_provider("rime")
        self.orch.on_stop_audio = handle.interrupt

        async def _await_playout() -> None:
            await handle.wait_for_playout()
            self.orch.finish_playback(generation_id)

        asyncio.create_task(_await_playout())


@server.rtc_session(agent_name="mechatronics-lab-assistant")
async def entrypoint(ctx: agents.JobContext) -> None:
    orch = orchestrator_module.Orchestrator()

    session = AgentSession(
        stt=deepgram.STT(api_key=config.DEEPGRAM_API_KEY, model="nova-3", language="en"),
        vad=silero.VAD.load(),
        tts=rime.TTS(
            api_key=config.RIME_API_KEY,
            model=config.RIME_MODEL_ID,
            speaker=config.RIME_SPEAKER,
            audio_format=config.RIME_AUDIO_FORMAT,
        ),
    )

    @session.on("user_interruption_detected")
    def _on_interruption(ev) -> None:
        # VAD-detected barge-in while the agent is speaking: freeze elapsed
        # playback time now (architecture §2.2), stop audio, and tag the
        # unheard remainder [interrupted] before the corrected transcript
        # even arrives.
        result = orch.on_speech_started_by_user()
        if result is not None:
            logger.info("barge-in: heard %d words, remainder=%r", result.words_heard, result.remainder_text)

    await session.start(room=ctx.room, agent=LabAssistant(orch, room=ctx.room))


if __name__ == "__main__":
    agents.cli.run_app(server)
